---
# handlers file for ansible-role-containerd
- name: enabled-containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    masked: no
- name: restart-containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
