---
## Install package and dependencies for ubuntu
- name: Install Dependencies for Debian
  apt:
    name: "{{ item }}"
    state: latest
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', "gnupg", "lsb-release", "net-tools" ]
